Always PR

diff --git a/.github/workflows/autopr.yml b/.github/workflows/autopr.yml
--- a/.github/workflows/autopr.yml
+++ b/.github/workflows/autopr.yml
@@ -55,20 +55,15 @@ jobs:
         set -x
         echo "PICKRESULT<<EOF" >> $GITHUB_OUTPUT
         echo "Pick up commits:" >> $GITHUB_OUTPUT
-        RANGE=$(git rev-list ${{github.event.before}}..${{github.event.after}} --reverse)
-        if [ $? -eq 0 ]; then # multiple commits
-          for commit in $RANGE; do
-            echo "" >> $GITHUB_OUTPUT
-            MSG=$(git cherry-pick -X theirs $commit)
-            if [ $? -ne 0 ]; then
-              echo "Failed to cherry-pick $commit" >> pick_up_failure.log
-            fi
-            echo "$MSG" >> $GITHUB_OUTPUT
-          done
-        else
+        RANGE=$(git rev-list ${{github.event.before}}..${{github.event.after}} --reverse || echo ${{github.event.after}})
+        for commit in $RANGE; do
           echo "" >> $GITHUB_OUTPUT
-          git cherry-pick -X theirs ${{github.event.after}} >> $GITHUB_OUTPUT
-        fi
+          MSG=$(git cherry-pick -X theirs $commit)
+          if [ $? -ne 0 ]; then
+            echo "Failed to cherry-pick $commit" >> pick_up_failure.log
+          fi
+          echo "$MSG" >> $GITHUB_OUTPUT
+        done
         echo "EOF" >> $GITHUB_OUTPUT
         if [ -s pick_up_failure.log ]; then
           git add pick_up_failure.log
